name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.config', '**/*.csproj', '**/global.json', '**/Directory.Build.props', '**/Directory.Build.targets', '**/.editorconfig') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore NuGet packages
      run: dotnet restore src/StartFromRepo.sln

    - name: Build
      run: dotnet build src/StartFromRepo.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/Tests/StartFromRepo.Tests.csproj --configuration Release --no-build --verbosity normal
